import React from 'react';
import { AlertTriangle, Brain, Flag } from 'lucide-react';

interface AIContentWarningProps {
  onReportIssue?: () => void;
  className?: string;
}

const AIContentWarning: React.FC<AIContentWarningProps> = ({ onReportIssue, className = "" }) => {
  return (
    <div className={`bg-amber-50 border border-amber-200 rounded-lg p-4 ${className}`}>
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0">
          <div className="w-8 h-8 bg-amber-100 rounded-full flex items-center justify-center">
            <Brain className="w-4 h-4 text-amber-600" />
          </div>
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            <h4 className="text-sm font-semibold text-amber-800">AI-Generated Content</h4>
          </div>
          <p className="text-sm text-amber-700 leading-relaxed mb-3">
            This content was generated by AI and should be used as a <strong>supplementary tool</strong> only. 
            Always refer to the original video for complete accuracy and context. AI may miss nuances or make interpretation errors.
          </p>
          {onReportIssue && (
            <button
              onClick={onReportIssue}
              className="inline-flex items-center gap-1 text-xs font-medium text-amber-700 hover:text-amber-800 transition-colors"
            >
              <Flag className="w-3 h-3" />
              Report an issue
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIContentWarning;